### ISSUE TITLE
چرا کار نمیکنه

### ISSUE THREAD

**Issue by ircfspace** [Begzar/BegzarApp#1]
این ایشو رو الکی زدم، که اولین ایشو توسط من ثبت شه :‌)

**Comment by Begzar** [comment]
> این ایشو رو الکی زدم، که اولین ایشو توسط من ثبت شه :‌)

یه سکته ناقص زدیم همه باهم ... :(

**Comment by efithatkid** [comment]
واقعا کار نمیکنه lol
رو huawei nova 7i وقتی باز میکنم یه صفحه blank میاد

**Comment by amirrezabi** [comment]
سلام ،،متاسفانه روی گوشی من (huawei y8p ) کار نمیکنه ،،یعنی وقت برنامه رو باز میکنم یه صفحه خالی  میاد و همونجوری میمونه

**Comment by chelsi4030** [comment]
> > این ایشو رو الکی زدم، که اولین ایشو توسط من ثبت شه :‌)
> 
> یه سکته ناقص زدیم همه باهم ... :(

فکر کنم روی گوشی های هواوی مشکل داره

**Comment by Begzar** [comment]
دوستای گلم,
گویا رو گوشی های هواوی نرم افزار مشکل داره 
هنوز دقیق نمیدونیم جریان چیه, ولی احتمالی که دادیم برای این باشه که از سرویس های google برای دریافت آنالایزیک های نرم افزار
استفاده میکنیم و شاید برای همین هواوی تحریمه و اپ کار نمیکنه.
روی جزیات کار میکنیم و خبر نهایی رو توی توییتر منتشر میکنیم.
