### ISSUE TITLE
تونل کردن برنامه ها و اندروید تی وی

### ISSUE THREAD

**Issue by smarteep** [Begzar/BegzarApp#13]
سلام، لطفا امکان این رو بذارید که روی همه برنامه ها اجرا نشه و خودمون انتخاب کنیم روی چه اپ هایی فیلترشکن کار کنه
برای اندروید تی وی هم بهینه کنید تا روی تلویزیون بتونیم اجرا کنیم

**Comment by Begzar** [comment]
سلام

به زودی ورژن جدید تمام این امکانات رو داره، صبور باشید.
