### ISSUE TITLE
درخواست قرار دادن برنامه در پلی استور

### ISSUE THREAD

**Issue by NIKJOO** [Begzar/BegzarApp#14]
با سلام و وقت بخیر
لطفا" برنامه رو داخل پلی استور قرار بدید ؛ چون در برخی کانال های تلگرامی دیدم که دارن از برنامه شما فورک میزنن تا داخل پلی استور قرار بدن ، اینکار لطمه زیادی به وجهه برنامه ای که شما بنیان اون رو بنا کردید وارد میکنید و باعث عدم اعتماد کاربران به ریپوی اصلی میشه

با تشکر

**Comment by Begzar** [comment]
سلام
روند انتشار اپلیکیشن در گوگل پلی عوض شده و قوانین بسیار سفت و سختی اوردن، حداقل 20 روز زمان نیازه برای انتشار اگر تمامی مراحل به درستی و به موقع انجام بشه.
مشکل بعدی اکانت گوگل پلی هست که درحال پیگیری هستیم و اینکه اگر در این مراحل انتشار اشتباهی صورت بگیره اکانت رو متاسفانه بن میکنن ( ربطی هم به فیلترشکن نداره و روی هر اپی این حساسیت وجود داره)

درحال حاضر داریم روی نرم افزار کار میکنیم شرایطشو مهیا میکنیم برای انتشار روی گوگل پلی، زمان بر هست متاسفانه
