### ISSUE TITLE
کار نمیکنه

### ISSUE THREAD

**Issue by MrAbolfazlNorouzi** [Begzar/BegzarApp#2]
یه صفحه سیاهه فقط 
![Screenshot_20241018_172950_cloud begzar begzar](https://github.com/user-attachments/assets/911a4747-f6b1-497a-a8f7-8b6e8ec41bf6)

**Comment by Begzar** [comment]
سلام
نسخه اندرویدتون چنده؟
کدوم ورژن اپ رو نصب کردین؟

**Comment by MrAbolfazlNorouzi** [comment]
سلام
نسخه v7a نصب میشه رو گوشیم 
پایینم اطلاعات اندروید گذاشتم 
گوگل پلی هم ندارم چون هواوی گوشیم
![Screenshot_20241018_190909](https://github.com/user-attachments/assets/fe574a0f-6a55-4118-9dac-90618497236b)

**Comment by Siamakka** [comment]
برای من هم همین مشکل رو داره.
هر دو نسخه رو نصب کردم و مشکل برطرف نشد.
![photo_2024-10-18_19-18-44](https://github.com/user-attachments/assets/21999765-4211-47d9-89ee-ecbbe1c0077b)

**Comment by Begzar** [comment]
ممنون بابت گزارشتون، روی ورژن جدید این مشکل حل میشه به زودی...
