### ISSUE TITLE
تلویزیون‌های اندرویدی

### ISSUE THREAD

**Issue by kheiyal** [Begzar/BegzarApp#4]
سپاس از شما. لطفا برای تلویزیون‌های اندرویدی هم بهینه‌سازی کنید. اکثر برنامه‌های تولیدی برای گذر از فیلترینگ این موضوع رو نادیده می‌گیرند! برنامه‌هایی مثل هدیفای، مهسا، نیکا و ابلیویون نصب می‌شن و کارراه‌اندازند ولی برای تلویزیون بهینه و یوزرفرندلی نیستند! برنامه‌ی «بگذر» بعد نصب، شمایل برنامه و آیکون‌ها و… نصف‌ونیمه نمایش داده می‌شه! و تقریبا کارایی نداره!

**Comment by Begzar** [comment]
سلام دوست عزیز، برای اندروید تی وی یک نسخه دیگه اراعه میشه، و راحت میتونید استفاده کنید.

**Comment by mojtabas87** [comment]
ممنون ازت
بنظر منم گزینه های آندروید تی وی خیلی میتونند مفید باشند و بخش بزرگی از فیلترینگ موجود دور بزنن
امیدوارم موفق باشی و سلامت و خوشحال ممنون بابت زحمتی که میکشی
