### ISSUE TITLE
بیلد در گیت‌هاب

### ISSUE THREAD

**Issue by jaavid** [Begzar/BegzarApp#5]
سلام
به زودی با حمله آدمهای مختلفی مواجه میشوید!
همون کاری که با بقیه کردن، حتا هیدیفای رو زیر سوال بردن و گیر میدادن بهش

قبل از این اتفاقات از تجربه آبلیویون استفاده کنید و کلیدهای لازم رو توی بخش های امنیتی اکانت گیت‌هاب‌تون بزارید که لو نره، بیلد رو هم بزارید با اکشن‌های گیت‌هاب همینجا انجام بشه

حسن نیت بیشتر شما کمک میکنه دردسرهای بعدی کمتر بشه و از ادامه مسیر دلسرد و ناامید نشید(امیدوارم)

**Comment by Begzar** [comment]
سلام و درود هم وطن!
بله توی برنامه هامون هست.
سورس کد نرم افزار رو برای عرضه اولیه گذاشتیم ولی با توجه به استقبال بی نظیر دوستان.
صد درصد مسیر درستی رو پیش خواهیم گرفت که جای شک و شبهه ایی ایجاد نشه،
از شما هم بابت گوشزد کردن این موضوع نهایت تشکر رو دارم ❤️
