### ISSUE TITLE
امنیت پایین

### ISSUE THREAD

**Issue by Nimadark** [Begzar/BegzarApp#6]
هلو خاستم بگم امنیت اپت خیلی ضعیفه روش کار کن 💯 (:

https://api.nitrosub.site/sub/begzarvpn.php

رمزنگاری بسیار ایزی و ضعیف

دوست داشتی تلگرام پیاده بده بهت بگم چیکار کن (:
@NimaDark045

**Comment by Begzar** [comment]
سلام دوست خوبم، ممنونم بابت issue ایی که ثبت کردین ، نسخه اولیه نرم افزار توی گیتهاب هست در نسخه های بعدی برنامه اینه که ب صورت کامل سورس کد پابلیک بشه و نیازی به اینکریپت و دیکریپت کانفیگ ها نباشه.
چون طبیعتا کانفیگ ها میتونن مثل یک سابسکریپشن نرمال عمل کنند.
باز هم از شما و وقتی که گذاشتین کمال تشکر رو دارم.
